operate-first/service-catalog

README.md
app-config.prod.yaml
manifests/overlays/prod/kustomization.yaml
manifests/overlays/prod/route.yaml

The default route host name was too long for `tls-acme` so a certificate couldn't be created.
The new `DNS CNAME` record (service-catalog.operate-first.cloud) was already added.

fix: Change host for route

---

examples/components/service1.yaml
examples/components/service2.yaml
examples/components/service3.yaml
packages/app/package.json
packages/app/src/App.tsx
packages/app/src/components/Root/Root.tsx
packages/app/src/components/home/HomePage.tsx
yarn.lock

Resolves: #23 
This adds a homepage with logo, search and list of components as tiles - each is clickable and leads to component detail (same as clicking component name in the Catalog table)

feat: Add home page with catalog overview

---

app-config.dev.yaml
app-config.prod.yaml
packages/app/package.json
packages/app/src/App.tsx
packages/app/src/components/catalog/EntityPage.tsx
packages/backend/package.json
packages/backend/src/index.ts
packages/backend/src/plugins/badges.ts
yarn.lock

Resolves #19 
For now, only the [default](https://github.com/backstage/backstage/blob/master/plugins/badges-backend/src/badges.ts#L34-L100) badges are available, more can be added later.
I've tested it in a GitHub README.md file but GitHub doesn't have access to the site because I am running it in our private network (dev cluster). But when I tested it on a [different website](https://markdownlivepreview.com/) that uses my browser to do the requests it worked fine. 
So I think when the changes get pushed to production it will work fine.

feat(badges): Install badges plugin

---

README.md
app-config.yaml
manifests/base/deployment.yaml
manifests/overlays/dev/kustomization.yaml
manifests/overlays/dev/secret.yaml
manifests/overlays/prod/kustomization.yaml
manifests/overlays/prod/secret.enc.yaml
package.json

Fixes:
- Markdown inconsistencies in README (linted via https://github.com/DavidAnson/markdownlint)
- Environment variable `backend_secret` converted to uppercase per env variable convention
- Overlays simplified
- `BACKEND_SECRET` set automatically in `yarn dev`

chore: Tidy up manifests and readme

---

README.md
packages/app/package.json
packages/app/src/components/catalog/EntityPage.tsx
yarn.lock

Resolves #17 
As mentioned in #34, if the insights are private and the user is not a member of an org, he won't be able to see the plugin information.
Here is an example of a repo that has security alerts https://github.com/skopecky-test/vulpy.
How it looks:

feat: Install security insights plugin

---

packages/app/src/components/catalog/EntityPage.tsx

Since `security-insights` plugin requires rights to see security insights on a repository most people when looking at services won't have the required rights. I think the best solution is to remove it form the main overview screen of a service so errors don't pop up every time they load the page.

feat(security-insights): Remove secrity insights from the main view

---

manifests/base/kustomization.yaml
manifests/base/serviceaccount.yaml

Part of #12 
This service account is required by the `k8s plugin` and is required to merge before <put pr here> is merged so that the token can be encrypted into the production secret manifest.

feat(k8s-plugin): Add service account for plugin

---

app-config.prod.yaml
app-config.yaml
manifests/overlays/prod/kustomization.yaml
manifests/overlays/prod/obc.yaml

Part of #13
- Add creation of s3 bucket on prod deployment and configure the backstage publisher with the generated `secret`/`configMap`
- Switch default docs building to `local` for development setup

feat(techdocs): Setup awsS3 as storage solution for techdocs publishing

---

packages/backend/src/plugins/permission.ts

Rename the permission policy because it was still using the default name from the backstage documentation.

chore: Rename permission policy

---

.github/actions/docs-dispatch/action.yaml
.github/workflows/techdocs-generate-and-publish.yaml
.github/workflows/techdocs.yaml
.pre-commit-config.yaml
app-config.prod.yaml

Resolves #13
This implements the 2nd solution in the issue referenced above. It can handle multiple documentation directories, one for each service in a single repository.
The workflow `techdocs-publisher.yaml` would live in this repository and it would handle building&publishing of the documentation.
The second workflow `techdocs.yaml` is required to send the [dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) events to the publisher. We would add this workflow to repositories that host the documentation.

feat(techdocs): Add github workflows for publisher and listener

---

manifests/base/deployment.yaml
manifests/base/kustomization.yaml

Part of #55
Add labels to manifests so that the k8s plugin can be utilized in the service catalog component.

feat: Add common labels to manifests

---

app-config.yaml
packages/app/src/components/catalog/EntityPage.tsx

Part of #55 
Is needed for creating a service catalog entity in service catalog ([operate-frist/apps#2205](https://github.com/operate-first/apps/pull/2205), [operate-frist/apps#2221](https://github.com/operate-first/apps/pull/2221))
Changes:
- Allow reading from `argocd.operate-first.cloud` domain to be able to load `argoCD` API reference 
- Add resource entity page
- Allow backstage to load `domain`, `API` and `resource` entities

feat: Add necessary configuration for new entities

---

manifests/base/deployment.yaml

Resource limits and requests are placed in the wrong path, fix this by placing them in `.spec.template.spec.containers[0]`.

fix: Resource limits for deployment

---

manifests/base/service.yaml

Forgot to do this while changing the deployment labels, sorry about that.

fix: Reference the correct label in service manifest

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Resolves #72 
For now I have created following issue templates:
If you think there should be any other templates present or you want some changes in current please let me know

feat: Add issue templates for service catalog

---

.github/workflows/techdocs.yaml

By creating a new entity setup we changed the catalog entity name from `service-catalog` to `backstage`. We need to reflect that change in the workflow that sends dispatch to build documentation.

chore: Fix entity name for the new catalog layout

---

README.md

Resolves #88 
- Add tags and logo to README
- Update some `README` sections with the section from the documentation.
Later down the line we can design a logo with the same style as the OPF one.

feat: Add tags and logo to readme

---

manifests/base/postgres.yaml

The database got filed up again since the backups were too big in size.
- Reduce retention policy to 7 days
- Increase storage size from `1 Gi` to `2 Gi`
Hopefully this should prevent any future problems with the storage and database.

fix: Reduce db backup retention, increase storage size

---

app-config.prod.yaml
manifests/base/deployment.yaml

Part of #59 
- Add tokens secret to deployment.
- Add configurations for our manged clusters to prod app config overlay 
- Reloader is already deployed at [here](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/reloader/pods) so I don't think I need to do any setup at apps repo.

feat: Add configs for all clusters to prod

---

.env.example
app-config.dev.yaml
app-config.local.yaml
app-config.prod.yaml
app-config.yaml
docs/contributing.md

Simplify the local dev setup a tiny bit:
- Make Dev github auth setting available at local deployment only
- Fetch remote catalog in prod only
- Add env variable for relative local import of catalog files
/cc @SamoKopecky

chore: Simplify local dev config a bit

---

packages/app/src/components/home/HomePage.tsx

Since we're about to start using `.metadata.title`, it only make sense to use this display name on the HomePage as well.. EntityPage uses it by default.
/cc @SamoKopecky

fix: Use .metadata.title on Home page when available

---

manifests/base/postgres.yaml

DB volume got used up again I think this time its because I understood the configuration incorrectly and thought the old value would keep 1 full and 6 differential backups, it seems like its keeping 7 full backups instead of just 1 full backup.
This change should tell the operator to only keep 1 full backup.

fix: Use the correct value for retention-full

---

docs/contributing.md
manifests/base/deployment.yaml
manifests/overlays/dev/secret.yaml
manifests/overlays/prod/kustomization.yaml

- Add better documentation
- Add default values to plugin secrets
- Move `service-catalog-k8s-plugin-tokens` secret requirement from base overlay to prod

chore: Improve dev overlay for k8s deployment

---

.s2iignore
app-config.dev.yaml
app-config.local.yaml
app-config.prod.yaml
manifests/components/rbac/role.yaml
packages/backend/src/index.ts
packages/backend/src/plugins/cluster-status.ts
plugins/cluster-status-backend/.eslintrc.js
plugins/cluster-status-backend/README.md
plugins/cluster-status-backend/package.json
plugins/cluster-status-backend/schema.d.ts
plugins/cluster-status-backend/src/index.ts
plugins/cluster-status-backend/src/run.ts
plugins/cluster-status-backend/src/service/router.ts
plugins/cluster-status-backend/src/setupTests.ts
plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
plugins/cluster-status-backend/src/statusCheck/kubernetesApi.ts
plugins/cluster-status-backend/src/types/types.ts
yarn.lock

Part of #102 
Create a plugin that will server as the backend for showing the status of clusters.
Blocked by https://github.com/operate-first/apps/pull/2439
Plugin API has 2 endpoints:
- `{addr}/api/cluster-status/status/{cluster-name}` -- get status for one chosen cluster
- `{addr}/api/cluster-status/status` -- get status for all configured clusters
Plugin adds a top level configuration field in the config files:
- `.clusterStatus.acmCluster` -- name of the ACM cluster to query for the status of all other configured clusters
Documentation will be added later to the backstage docs page.

feat: Create cluster status backend plugin

---

docs/k8s-plugin-configuration.md
mkdocs.yaml

Part of #59
Add documentation describing the k8s plugin configuration.
Link number 8 depends on https://github.com/operate-first/apps/pull/2334 to merged.

docs: Add docs for k8s plugin configuration

---

.s2ibase

Resolves: #110
Replaces: #115
We've discovered `gzip` is removed from latest `ubiX/minimal` base images... I'll investigate further. For now, let's lock to previous revision.
https://catalog.redhat.com/software/containers/ubi9/nodejs-16-minimal/61a6059abfd4a5234d59621f?tag=1-67&push_date=1663685796000&container-tabs=packages
https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?tag=9.0.0-1644&push_date=1663685323000&container-tabs=packages

hotfix: Lock S2I base image

---

packages/app/src/App.tsx
packages/app/src/clusterClient.ts
packages/app/src/components/Root/Root.tsx
packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
yarn.lock

Part of #102 
Add a frontend client to call the required endpoints for the backend `cluster-status` plugin.
Add a single page to show the overlap of configured cluster and resources with `kind: cluster`. Each entry displays the cluster name, status and description. It uses the data from the backend `cluster-status` plugin. See the image bellow for an example.

feat: Add clusterwide status page

---

plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts

The check whether a cluster name existed in the config file was incorrect.

fix: Correctly check if cluster name exists in config

---

manifests/overlays/dev/kustomization.yaml

This patch is required so that the k8s plugin can be used in dev overlay.

fix: Add patch for service account name

---

packages/app/src/components/catalog/shared/InfoCard.tsx

Resolves #53 
In order to add the logo some restructuring of the info card was needed.
If a logo annotation is present:
If it isn't:

feat: Add entity logo to info card

---

app-config.dev.yaml
app-config.local.yaml
app-config.prod.yaml
packages/backend/package.json
packages/backend/src/plugins/search.ts
yarn.lock

Depends on #133 
- Setup search to use postgres search
- Add configuration option for initial delay and set it to 30 sec for a k8s deployment so that the backend has time to start since the search plugin communicates with the backend to create indexes. [search docs](https://backstage.io/docs/features/search/getting-started#backend)

feat: Setup postgres search

---

packages/app/package.json
packages/app/src/clusterClient.ts
packages/app/src/components/catalog/resource.tsx
packages/app/src/components/catalog/shared/ClusterStatus.tsx
packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
yarn.lock

Part of #102 
Create a better looking cluster resource page. Data for the tables is gathered from the `cluster-status` backend plugin. Individual tables are exported as components so they can be reused elsewhere.
How it looks:

feat: Add cluster details to individual clusters

---

plugins/rhacm-backend/src/helpers/config.ts

In case the config had more clusters defined, this method returns an `.data` array which is not consumable by `kuberntes/node-client`.

fix: Find hub cluster in config

---

packages/app/src/components/catalog/resource.tsx
packages/backend/src/plugins/catalog.ts
plugins/rhacm-backend/src/index.ts
plugins/rhacm-backend/src/providers/ManagedClusterProvider.ts
plugins/rhacm-backend/src/providers/index.ts

Create an automated catalog provider for Managed Clusters resources.
1. https://github.com/operate-first/service-catalog/commit/276065f841f38141e361882e833be67e0cf63d9f commit:
- Creates a `ManagedClusterProvider` which populates `Resource` catalog entity based on ACMs data.
- Resources are set to type of `kubernetes-cluster` in preparation for [`CatalogClusterLocator`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L43) from `backstage/kubernetes` plugin.
- Automatically populate links to OCP console, RHACM console and console.redhat.com.
2. https://github.com/operate-first/service-catalog/commit/39f8a70444e010df64e224e46d0d264530f33fbd commit:
- Creates a custom pre-processor catching all clusters created by the …

feat: Create catalog provider for ACM

---

plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx

Since the the type of the entities changed, `ClusterStatusPage` needs to be changed to work.
- Remove description for individual clusters, remove padding
How it looks:

feat: Adapt cluster page for backend refractor

---

packages/app/src/components/home/HomePage.tsx
plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx

Instead of querying all entities in the catalog and then filtering them, we can filter directly on the query.

refactor: Optimize catalog api fetch with filter

---

.github/workflows/techdocs-generate-and-publish.yaml
mkdocs.yaml

Part of #71 
Add support for mermaid diagrams into techdocs via [kroki](https://kroki.io/) which supports many more diagrams, see [upstream docs](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-add-mermaid-support-in-techdocs).

feat: Add support for mermaid diagrams in techdocs

---

packages/app/src/components/DeploymentStatusCard/DeploymentStatusCard.tsx
packages/app/src/components/catalog/component.tsx

Populate the "Deployments" status card with data:
e.g. image pull error - state of the pod is `Pending` and pod is reporting errors
Replaces the placeholder status card with a proper one.

feat: Create Kubernetes Pod status overview card

---

manifests/base/deployment.yaml

Part of #171 
This workaround might fix the issue see https://github.com/operate-first/service-catalog/issues/171#issuecomment-1305297972.

fix: Change HTTP probe to exec

---

manifests/base/deployment.yaml

Part of #171 
Add a longer timeout to the HTTP requests. I tested this out and it worked for 10+ hours in prod environment. Also change back to HTTP probe since the exec probe didn't solve the problem.

fix: Increase timeout for probes

---

manifests/base/kustomization.yaml
manifests/base/secret.yaml

Argocd is complaining about the secret located in this repository base manifests since the secret is getting created via an external secret.
Warning text:
```
Secret/service-catalog is part of applications service-catalog-smaug and cluster-resources-smaug
```

chore: Remove secret from base deployment

---

plugins/rhacm-backend/src/helpers/config.ts

Rather than raising a generic config error about `rhacm.hub` not being found in config, display more specific message in the logs.

fix: Raise proper error when hub cluster is undefined in the config

---

packages/app/src/components/LinkTiles/LinkTile.tsx
packages/app/src/components/LinkTiles/LinkTiles.tsx
packages/app/src/components/catalog/component.tsx
packages/app/src/components/catalog/domain.tsx
packages/app/src/components/catalog/resource.tsx
packages/app/src/components/catalog/shared/OverviewWrapper.tsx
packages/app/src/components/catalog/system.tsx

Resolves: https://github.com/operate-first/service-catalog/issues/183
Instead of a boring `EntityLinksCard`
Let's show something more interesting - `LinkTiles`:
It respects the entity page theme, so `Components` are displayed in different color than `Resources` etc.
We maintain the same logic for icon fetching as the `EntityLinksCard` so there should be no confusion.

feat: Create LinkTiles component

---

app-config.yaml
packages/app/package.json
packages/app/src/components/catalog/component.tsx
yarn.lock

Adds roadie backstage plugin and adds alerts to the component as a tab
Plugin requires token which has permission to get namespaces. More information can be found [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/observability/index#external-metric-query) . Till this token is created this PR is WIP.
Resolves #16

feat: Add prometheus alerts

---

docs/configuring-entities.md

Resolves #71
Add mermaid diagram and an explanation for our techdocs architecture.
/hold

docs: Add techdocs architecture explenation

---

plugins/rhacm-backend/package.json
plugins/rhacm-backend/src/helpers/config.test.ts
plugins/rhacm-backend/src/helpers/config.ts
plugins/rhacm-backend/src/helpers/kubernetes.test.ts
plugins/rhacm-backend/src/helpers/parser.test.ts
plugins/rhacm-backend/src/helpers/parser.ts
plugins/rhacm-backend/src/helpers/test_data/kubeconfig.yaml
plugins/rhacm-common/src/index.ts
yarn.lock

Part of #176 
Create tests for the functions in the `helpers` folder.

test: Add tests for config.ts and parser.ts

---

app-config.local.yaml
plugins/web-terminal/package.json
plugins/web-terminal/schema.d.ts
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
yarn.lock

This PR updates UI and add logic to handle token and cluster submission for the terminal. It uses subprotocols to transfer inputed data to websocket server for now is just dummy. On the Websocket server side it is expected that it will parse subprotocols and extract data from it. Cluster is inputed in a format `api.my.cluster.com:6443`
To actually display some data it needs running Websocket server without the server it will stay in loading state.

feat(SRE-portal): Update UI to support cluster and token input

---

plugins/web-terminal/schema.d.ts

Mandatory config of the plugin causes runtime issues in prod since it's not configured but included for some reason (even though the plugin is not actually installed in the instance):
```
Backend failed to start up Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'webTerminal' { missingProperty=webTerminal } at
at readConfigs (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/index.cjs.js:69:13)
at async Object.createRouter (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/index.cjs.js:225:24) …
```

fix: Fix build with webterminal internal plugin

---

plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
plugins/web-terminal/src/components/TerminalComponent/utils/index.ts
plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts

This PR adds REST requests to initialize devworkspace and adds subprotocols which are then send to the proxy. These subprotocols contain basic information so that proxy knows for which pod to finish initialization and connect to it.
This PR should be discussed simultaneously with PR that introduces websocket proxy
Related to: https://github.com/janus-idp/webterminal-proxy/pull/1

feat (SRE-portal): Client setup for webterminal

---

packages/app/package.json
packages/app/src/App.tsx
packages/app/src/components/LinkTiles/LinkTile.tsx
packages/app/src/components/Root/Root.tsx
packages/app/src/components/catalog/shared/InfoCard.tsx
packages/app/src/components/home/HomePage.tsx
packages/app/src/themes.tsx
yarn.lock

Various visual fixes:
- Use Operate First colors as a theme (light and dark)
- Set `<title>` on Home page (previously only the title available from initial HTML load was used - this got overriden on any page within Backstage, so when user goes to Home->Catalog->Home, the title stays with whatever title was used on the Catalog page...
- Add warning icon to the "No owner" in the info card.
- Add the same social links we have on operate-first.cloud website
- Align Home page filters to center of the screen

feat: Operate First theme

---

plugins/web-terminal/package.json
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx

Uses new annotation in resource `kubernetes.io/api-server` instead of having to input a cluster API server manually
Related to: https://github.com/janus-idp/backstage-plugins/pull/94
Part of: https://github.com/janus-idp/backstage-plugins/issues/81

feat: Use cluster annotation instead of form field

---

plugins/web-terminal/package.json
plugins/web-terminal/schema.d.ts
plugins/web-terminal/src/components/NamespacePickerDialog/NamespacePickerDialog.tsx
plugins/web-terminal/src/components/NamespacePickerDialog/index.tsx
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
plugins/web-terminal/src/components/TerminalComponent/utils/helpers.ts
plugins/web-terminal/src/components/TerminalComponent/utils/index.ts
plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts
yarn.lock

This PR adds a dropdown menu with all the namespaces in the cluster where user can choose proper namespace to start a pod in. This dropdown menu only displays if the request in default namespace (`openshift-terminal`). Chosen namespace is then used to initialize environment and is sent to the `webterminal-proxy`.
Example of form before first request:
When the request fails
*User must be able to read namespaces otherwise the list will be empty
Part of: https://github.com/operate-first/service-catalog/issues/213
**Edit** added functionality to input default namespace which will be used this configuration is optional and if not specified it uses `openshift-terminal` Example of usage:
```
webTerminal:
webSocketUrl: "ws://localhost:8080/"
defaultNamespace: "namespace"
```
**Edit 2** Updated …

feat: Enable changing of namespace in UI

---

manifests/base/deployment.yaml
manifests/base/kustomization.yaml
manifests/base/route-webterminal.yaml
manifests/base/service.yaml
manifests/overlays/prod/kustomization.yaml
manifests/overlays/prod/route-webterminal.yaml

This PR adds `webterminal` sidecar and routes that expose this sidecar on `service-catalog` service. 
This PR requires uploaded image on quay

feat: Add deployment and routes for webterminal-proxy

---

packages/app/package.json
packages/app/src/components/catalog/shared/RunBooksCard.tsx
yarn.lock

This PR introduces a component that renders markdown runbooks it also contains `EntityPrometheusAlertCard` to allow for easier share of data between these two components.
Example:
To have this component working properly we have ensure following items are present:

feat: Create runbooks component

---

packages/backend/src/plugins/catalog.ts

This PR fixes issue with annotations not being properly added to entity in preprocessing.
Before fix:
After fix:
Also fixes in the second commit typo in `prometheus.io/alert` :no_mouth:

fix: Fix originLocation.type check and prometheus.io/alert annotation

---

packages/app/src/components/catalog/shared/RunBooksCard.tsx

Adds a functionality that converts `github.com` links (if present) to `raw.githubusercontent.com` to enable fetch of data from the website, it also makes adjustments to ensure that the alertData are properly propagated when user click on row.

feat: Convert github link to raw.githubusercontent

---

manifests/base/service.yaml

When there are two and more ports specified in the Service they require name. This PR adds name for these ports (More info can be found [here](https://access.redhat.com/solutions/6106961)

fix: Service ports missing name

---

app-config.prod.yaml
packages/app/src/components/catalog/resource.tsx

This PR adds SRE portal page to resource entity. 
SRE portal features:
Example of running page:

feat: Add SRE portal to service catalog

---

app-config.local.yaml
app-config.prod.yaml
plugins/web-terminal/schema.d.ts
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts

This PR updates frontend to use webterminal-proxy for REST requests instead of direct requests against cluster. This done to avoid issue when response from the cluster does not include `Access-Control-Allow-Origin` and therefore output of the request cannot be parsed.

feat: Use REST proxy instead of direct cluster requests
