- OWNERS
Resolves #3 
OWNERS file was taken from the [template repository](https://github.com/operate-first/template/blob/main/OWNERS).
> feat: Add owners file

- README.md
> feat(docs): Improve documentation

- app-config.prod.yaml
- app-config.yaml
Update `baseUrl` and location for catalog definition files.
> feat(prod): Update configs for production

- manifests/base/deployment.yaml
Remove the security context from deployment that I forgot to remove earlier because I was testing something.
> fix(prod): Remove security context from deployment

- examples/components/service1.yaml
- examples/components/service2.yaml
- examples/components/service3.yaml
- packages/app/src/components/home/HomePage.tsx
SSIA, related to https://github.com/operate-first/apps/pull/2127
> fix: Simplify logo annotation

- packages/app/src/components/home/HomePage.tsx
> fix: Make all home page tiles same height

- app-config.yaml
- manifests/base/deployment.yaml
- manifests/overlays/prod/secret.enc.yaml
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- yarn.lock
This PR adds ArgoCD plugin to the service page. Plugin shows name, sync status, health and when it was last synced:
Resolves #20
> feat: Add ArgoCD plugin to service catalog

- README.md
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- yarn.lock
Resolves #18 
The layout is not final, I think we can tinker with it when have all the plugins installed.
> feat: Install github insights plugin

- README.md
- app-config.local.yaml
> chore: Fix repo pointers

- app-config.yaml
> fix: Override default CSP directive for images

- packages/app/src/components/catalog/EntityPage.tsx
> feat: Hide grafana plugin if not available

- manifests/base/deployment.yaml
- manifests/base/postgres.yaml
> feat: Increase CPU limits for postgres and catalog

- packages/app/src/components/home/HomePage.tsx
> fix: Remove streching from home icons

- packages/backend/src/plugins/permission.ts
Resolves #54 
I also reworked the permission policy a bit to make future permission changes easier.
> feat: Allow everyone to refresh an entity

- .env.example
- README.md
- app-config.dev.yaml
- app-config.local.yaml
- app-config.prod.yaml
- manifests/base/deployment.yaml
- manifests/components/rbac/kustomization.yaml
- manifests/components/rbac/role.yaml
- manifests/components/rbac/rolebinding.yaml
- manifests/overlays/dev/kustomization.yaml
- package.json
- packages/app/package.json
- packages/app/src/components/catalog/EntityPage.tsx
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/plugins/kubernetes.ts
- yarn.lock
Resolves #12 
Install k8s plugin to show related resources in kube clusters.
Configure the plugin for:
- Smaug cluster in the prod overlay.
- Local clusters in local/dev cluster overlays.
> feat(plugins): Install and configure kuberntes plugin for smaug cluster

- manifests/base/postgres.yaml
Resolves #48 
- Add incremental backups every day other then Sunday and full backup every Sunday. 
- Retention policy for backups set to 14 days.
> feat(db): Add backup schedule and retention policy

- .github/actions/build-service-catalog/action.yaml
- .github/actions/set-expiration/action.yaml
- .github/actions/test/action.yaml
- .github/workflows/pr.yaml
- .github/workflows/push.yaml
- .s2ibase
This PR creates Github actions CI which should on each push to main build image which is pushed to quay repository, it also runs tests on each PR
Part of: #62
> feat: Prepare CI to build images

- packages/backend/package.json
- packages/backend/src/plugins/permission.ts
- yarn.lock
Part of: #103 
For now at least allow orphan cleanup. Automated solution in a follow up PR.
> fix: Allow delete of orphans

- app-config.prod.yaml
> feat: Add jerry to cluster configs

- .github/workflows/codeql-analysis.yml
I want to see if we can benefit from Github security plugin - this should populate the scorecard. :)
> chore: Setup code scanning

- packages/backend/package.json
- yarn.lock
> fix: Internal plugin missing from dependencies

- plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
> fix: Handle a case where claim is undefined

- packages/app/src/components/Root/Root.tsx
> feat: Add docs icon to nav bar

- packages/app/src/components/Root/Root.tsx
> fix: Small sidebar tweaks

- packages/app/src/components/catalog/shared/InfoCard.tsx
> fix: Add nowrap to InfoCard name column

- .aicoe-ci.yaml
- packages/backend/build-image.sh
> chore: Remove build section from .aicoe-ci.yaml

- packages/backend/package.json
- plugins/cluster-status-backend/package.json
- yarn.lock
This will remove some duplicate packages and prevent this warning from popping up.
> chore: Remove duplicate packages

- packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
> chore: Simplify cluster status page

- manifests/base/deployment.yaml
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/metrics.ts
- packages/backend/src/plugins/healthcheck.ts
- yarn.lock
Resolves https://github.com/operate-first/service-catalog/issues/63
> feat: Enable metrics and healthz endpoints

- OWNERS
> chore: Update owners

- packages/app/src/App.tsx
> chore: Remove unused routes

- plugins/rhacm-backend/src/helpers/kubernetes.ts
- plugins/rhacm-backend/src/service/router.ts
Create a proper handler for the k8s API. [This](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/middleware/errorHandler.ts) default backstage error handler makes sure the backend answers on errors.
> feat: Add proper error handler for k8s api

- plugins/rhacm-backend/src/helpers/config.ts
Remove `getClustersFromConfig` function since it is not used anywhere.
> chore: Remove unused function

- manifests/overlays/dev/kustomization.yaml
> fix: Add secret as a resource in dev manifests

- app-config.yaml
- packages/backend/package.json
- yarn.lock
> feat: fix OCM and allow new API locations

- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/components/Root/Root.tsx
- packages/app/src/components/catalog/component.tsx
- packages/app/src/components/catalog/domain.tsx
- packages/app/src/components/catalog/shared/utils.tsx
- packages/app/src/components/catalog/system.tsx
- packages/app/src/components/home/HomePage.tsx
- packages/app/src/components/search/SearchPage.tsx
- packages/backend/package.json
- packages/backend/src/plugins/search.ts
- yarn.lock
Various usability fixes and improvements:
- Adjust search to properly search by TechDocs and ADRs and display the same icons as sidebar
- Add ADR link to sidebar and to Domain
- Add quick filters to homepage
> feat: tweaks for ADRs, tech docs and home page

- .github/workflows/techdocs-generate-and-publish.yaml
Should allow both `workflow_dispatch` and `repository_dispatch` for docs generator.
> chore: Allow manual techdocs generator trigger

- .github/workflows/techdocs.yaml
> docs: Fix entity for which we generate docs

- app-config.dev.yaml
- app-config.local.yaml
- app-config.prod.yaml
- packages/app/package.json
- packages/backend/package.json
- yarn.lock
> chore: Upgrade ocm plugins to the latest version

- .github/workflows/backstage-tag.yaml
- README.md
- Add a workflow that will create a new tag based on the changes to `backstage.json`
- Update some old information about the service catalog in README
- Reference the correct repository in the README header
> docs: Update readme to show the current backstage version

- plugins/web-terminal/README.md
This PR creates simple README which explains what this plugin does and how it can be used.
> feat: Add simple README for the plugin

- manifests/base/kustomization.yaml
> fix: Change address of webterminal image on quay

- plugins/web-terminal/README.md
> feat(webterminal-plugin): Update config example in README
